void get_b_val(unsigned char* a)
{
// STORE ALL SAMPLE VALUES IN EEPROM
// GET THE MAX VALUES OUT OF ALL VALUES 
}

void get_w_val(unsigned char* a)
{
// STORE ALL SAMPLE VALUES IN EEPROM
// THESE SAMPLE VALUES WILL BE TAKEN ONLY FROM WHITE PART 
// GET THE MAX VALUES OUT OF ALL MIN VALUES 
}
